import type { ComponentDefinition, ComponentKind } from './types'

export const COMPONENTS: Record<ComponentKind, ComponentDefinition> = {
  wind: {
    kind: 'wind',
    name: 'Turbina eólica',
    shortName: 'Eólica',
    description: 'Produce 2 MW por ciclo directamente, sin generar calor.',
    icon: '≋',
    cost: 50,
    capacity: 0,
    directEnergy: 2,
  },
  solar: {
    kind: 'solar',
    name: 'Panel solar',
    shortName: 'Solar',
    description: 'Produce 4 MW por ciclo directamente, sin una red térmica.',
    icon: '☀',
    cost: 110,
    capacity: 0,
    directEnergy: 4,
    unlockEnergy: 100,
  },
  battery: {
    kind: 'battery',
    name: 'Batería de red',
    shortName: 'Batería',
    description: 'Almacena energía renovable y la devuelve cuando la producción directa se detiene.',
    icon: '▤',
    cost: 350,
    capacity: 0,
    storageCapacity: 500,
    storageRate: 8,
    unlockEnergy: 1500,
  },
  controller: {
    kind: 'controller',
    name: 'Controlador de red',
    shortName: 'Control',
    description: 'Automatiza baterías: reserva excedentes sobre 10 MW y cubre déficits de la red.',
    icon: '⌘',
    cost: 800,
    capacity: 0,
    unlockEnergy: 7500,
  },
  core: {
    kind: 'core',
    name: 'Núcleo térmico',
    shortName: 'Núcleo',
    description: 'Produce 12 de calor por ciclo. Sin una salida térmica acabará explotando.',
    icon: '✦',
    cost: 180,
    capacity: 150,
    production: 12,
    fuelCycles: 300,
    refuelCost: 120,
    unlockEnergy: 750,
  },
  thorium: {
    kind: 'thorium',
    name: 'Reactor de torio',
    shortName: 'Torio',
    description: 'Produce 28 de calor por ciclo con una vasija de alta capacidad.',
    icon: '◈',
    cost: 900,
    capacity: 420,
    production: 28,
    unlockEnergy: 5000,
    fuelCycles: 450,
    refuelCost: 900,
  },
  fusion: {
    kind: 'fusion',
    name: 'Reactor de fusión',
    shortName: 'Fusión',
    description: 'Produce 72 de calor por ciclo. Requiere una red industrial para controlarlo.',
    icon: '✺',
    cost: 4500,
    capacity: 950,
    production: 72,
    unlockEnergy: 50000,
    fuelCycles: 600,
    refuelCost: 4500,
  },
  exchanger: {
    kind: 'exchanger',
    name: 'Intercambiador',
    shortName: 'Interc.',
    description: 'Extrae hasta 10 de calor por ciclo y permite extender la red.',
    icon: '⇄',
    cost: 60,
    capacity: 240,
    transferRate: 10,
    unlockEnergy: 750,
  },
  pipe: {
    kind: 'pipe',
    name: 'Tubería térmica',
    shortName: 'Tubería',
    description: 'Transporta hasta 6 de calor por ciclo a través de la planta.',
    icon: '━',
    cost: 25,
    capacity: 90,
    transferRate: 6,
    unlockEnergy: 750,
  },
  accumulator: {
    kind: 'accumulator',
    name: 'Acumulador térmico',
    shortName: 'Depósito',
    description: 'Almacena hasta 900 de calor para estabilizar variaciones de la red.',
    icon: '▣',
    cost: 140,
    capacity: 900,
    transferRate: 12,
    unlockEnergy: 750,
  },
  generator: {
    kind: 'generator',
    name: 'Turbina generadora',
    shortName: 'Turbina',
    description: 'Convierte hasta 8 de calor adyacente en energía y créditos.',
    icon: 'ϟ',
    cost: 160,
    capacity: 180,
    conversionRate: 8,
    unlockEnergy: 750,
  },
  cooler: {
    kind: 'cooler',
    name: 'Torre de enfriamiento',
    shortName: 'Enfriador',
    description: 'Disipa hasta 12 de calor adyacente por ciclo.',
    icon: '❄',
    cost: 90,
    capacity: 260,
    coolingRate: 12,
    unlockEnergy: 750,
  },
}

export const COMPONENT_ORDER: ComponentKind[] = ['wind', 'solar', 'battery', 'controller', 'core', 'thorium', 'fusion', 'generator', 'cooler', 'exchanger', 'pipe', 'accumulator']
