import { COMPONENT_ORDER, resistanceFromCapacityAndFlow } from './balance'
import type { ComponentDefinition, ComponentKind } from './types'

export const COMPONENTS: Record<ComponentKind, ComponentDefinition> = {
  wind: { kind: 'wind', name: 'Turbina eólica', shortName: 'Eólica', description: 'Produce 0,2 E/s durante 10 segundos: 2 E por cada reconstrucción de ₡1.', icon: '≋', cost: 1, capacity: 0, directEnergy: 0.2, fuelCycles: 10, refuelCost: 1 },
  solar: { kind: 'solar', name: 'Panel solar', shortName: 'Solar', description: 'Produce 100 E/s durante 150 segundos: 15.000 E por reconstrucción.', icon: '☀', cost: 10_000, capacity: 0, directEnergy: 100, fuelCycles: 150, refuelCost: 10_000, tech: 'solar' },
  sales: { kind: 'sales', name: 'Oficina de ventas', shortName: 'Ventas', description: 'Vende 50 E/s. Conserva su potencia base al avanzar de tier.', icon: '₡', cost: 250, capacity: 0, salesRate: 50 },
  sales2: { kind: 'sales2', name: 'Oficina de ventas II', shortName: 'Ventas II', description: 'Vende 30.000 E/s y multiplica la capacidad comercial de las redes avanzadas.', icon: '₡', cost: 5_000_000, capacity: 0, salesRate: 30_000, tech: 'thorium' },
  battery: { kind: 'battery', name: 'Batería de red', shortName: 'Batería', description: 'Añade 10.000 E de almacenamiento al mapa; solo aumenta mediante sus propias mejoras.', icon: '▤', cost: 25_000, capacity: 0, storageCapacity: 10_000, tech: 'solar' },
  research: { kind: 'research', name: 'Instalación de I+D', shortName: 'I+D', description: 'Genera 1 RP/s de manera pasiva.', icon: '⌬', cost: 500, capacity: 0, researchRate: 1 },
  research2: { kind: 'research2', name: 'Centro de investigación II', shortName: 'I+D II', description: 'Genera 500 RP/s para sostener la investigación de tecnologías avanzadas.', icon: '⌬', cost: 50_000_000, capacity: 0, researchRate: 500, tech: 'thorium' },
  controller: { kind: 'controller', name: 'Controlador de red', shortName: 'Control', description: 'Aumenta 10 % almacenamiento y venta, hasta 50 %.', icon: '⌘', cost: 100_000_000, capacity: 0, controllerBonus: 0.1, tech: 'thorium' },
  core: { kind: 'core', name: 'Núcleo térmico', shortName: 'Núcleo', description: 'Produce 7.500 calor/s durante 200 segundos: 1,5 M de calor.', icon: '✦', cost: 1_000_000, capacity: 20_000, production: 7_500, fuelCycles: 200, refuelCost: 1_000_000, tech: 'thermal' },
  thorium: { kind: 'thorium', name: 'Reactor de torio', shortName: 'Torio', description: 'Produce 500.000 calor/s durante 300 segundos: 150 M de calor. Tolera 2,5 M de calor: si se supera, se avería.', icon: '◈', cost: 100_000_000, capacity: 2_500_000, production: 500_000, fuelCycles: 300, refuelCost: 100_000_000, tech: 'thorium' },
  fusion: { kind: 'fusion', name: 'Reactor de fusión', shortName: 'Fusión', description: 'Produce 10 M calor/s durante 300 segundos: 3 G de calor. Tolera 100 M de calor: si se supera, se avería.', icon: '✺', cost: 2_000_000_000, capacity: 100_000_000, production: 10_000_000, fuelCycles: 300, refuelCost: 2_000_000_000, tech: 'fusion' },
  planck: { kind: 'planck', name: "The Planck's Length", shortName: 'Planck', description: 'Reactor experimental del polígono de ensayos: 2,5 G calor/s durante 300 segundos. Tolera 10 G de calor, y ninguna red pequeña puede absorberlo.', icon: '✧', cost: 500_000_000_000, capacity: 10_000_000_000, production: 2_500_000_000, fuelCycles: 300, refuelCost: 500_000_000_000, tech: 'testsite' },
  generator: { kind: 'generator', name: 'Turbina generadora', shortName: 'Turbina', description: 'Convierte hasta 1.875 calor/s sin resistencia terminal y guarda una reserva de un ciclo para aguantar un bajón de producción.', icon: 'ϟ', cost: 50_000, capacity: 4_000, thermalResistance: 0, conversionRate: 1_875, tech: 'thermal' },
  generator2: { kind: 'generator2', name: 'Turbina generadora II', shortName: 'Turbina II', description: 'Conversor avanzado de Fusión: transforma 900.000 calor/s sin modificar las turbinas existentes. Guarda una reserva de un ciclo y tolera 3 M de calor.', icon: 'ϟ', cost: 150_000_000, capacity: 3_000_000, thermalResistance: 0, conversionRate: 900_000, tech: 'fusion' },
  cooler: { kind: 'cooler', name: 'Torre de enfriamiento', shortName: 'Enfriador', description: 'Disipa hasta 50.000 calor/s adyacente.', icon: '❄', cost: 1_000_000, capacity: 0, coolingRate: 50_000, tech: 'thorium' },
  exchanger: { kind: 'exchanger', name: 'Intercambiador', shortName: 'Interc.', description: 'Nodo térmico con resistencia 2,24. Tolera 2 M de calor; solo aumenta mediante sus propias mejoras.', icon: '⇄', cost: 50_000_000, capacity: 2_000_000, referenceTransferRate: 200_000, thermalResistance: resistanceFromCapacityAndFlow(2_000_000, 200_000), tech: 'thorium' },
  pipe: { kind: 'pipe', name: 'Tubería térmica', shortName: 'Tubería', description: 'Conduce calor a la velocidad que marca su resistencia 0,01. Tolera 200.000 de calor: si se supera, se avería.', icon: '━', cost: 10_000_000, capacity: 200_000, referenceTransferRate: 50_000, thermalResistance: 0.01, tech: 'thorium' },
  pipe2: { kind: 'pipe2', name: 'Tubería térmica II', shortName: 'Tubería II', description: 'Superconductor de Fusión: todas las Tuberías II conectadas entre sí reparten el calor por igual, y cualquier turbina pegada a la masa alcanza todo ese calor, no solo el de su vecina. Cuantas más juntes, más frío mantienes el reactor. Cada una tolera 10 M.', icon: '═', cost: 250_000_000, capacity: 10_000_000, referenceTransferRate: 1_967_347, thermalResistance: 1, tech: 'fusion' },
  accumulator: { kind: 'accumulator', name: 'Acumulador térmico', shortName: 'Depósito', description: 'Depósito de resistencia 24,75. Tolera 10 M de calor antes de averiarse.', icon: '▣', cost: 250_000_000, capacity: 10_000_000, referenceTransferRate: 100_000, thermalResistance: resistanceFromCapacityAndFlow(10_000_000, 100_000), tech: 'thorium' },
}
export { COMPONENT_ORDER }
