import { COMPONENT_ORDER, resistanceFromCapacityAndFlow } from './balance'
import type { ComponentDefinition, ComponentKind } from './types'

export const COMPONENTS: Record<ComponentKind, ComponentDefinition> = {
  wind: { kind: 'wind', name: 'Turbina eólica', shortName: 'Eólica', description: 'Produce 0,2 E/s durante 10 segundos: 2 E por cada reconstrucción de ₡1.', icon: '≋', cost: 1, capacity: 0, directEnergy: 0.2, fuelCycles: 10, refuelCost: 1 },
  solar: { kind: 'solar', name: 'Panel solar', shortName: 'Solar', description: 'Produce 100 E/s durante 150 segundos: 15.000 E por reconstrucción.', icon: '☀', cost: 10_000, capacity: 0, directEnergy: 100, fuelCycles: 150, refuelCost: 10_000, tech: 'solar' },
  sales: { kind: 'sales', name: 'Oficina de ventas', shortName: 'Ventas', description: 'Vende 50 E/s. Conserva su potencia base al avanzar de tier.', icon: '₡', cost: 250, capacity: 0, salesRate: 50 },
  sales2: { kind: 'sales2', name: 'Oficina de ventas II', shortName: 'Ventas II', description: 'Segundo tier comercial con valores semilla editables desde Debug.', icon: '₡', cost: 250, capacity: 0, salesRate: 50, tech: 'thorium' },
  battery: { kind: 'battery', name: 'Batería de red', shortName: 'Batería', description: 'Añade 100.000 E de almacenamiento al mapa; solo aumenta mediante sus propias mejoras.', icon: '▤', cost: 50_000, capacity: 0, storageCapacity: 100_000, tech: 'solar' },
  research: { kind: 'research', name: 'Instalación de I+D', shortName: 'I+D', description: 'Genera 1 RP/s de manera pasiva.', icon: '⌬', cost: 500, capacity: 0, researchRate: 1 },
  research2: { kind: 'research2', name: 'Centro de investigación II', shortName: 'I+D II', description: 'Segundo tier científico con valores semilla editables desde Debug.', icon: '⌬', cost: 500, capacity: 0, researchRate: 1, tech: 'thorium' },
  controller: { kind: 'controller', name: 'Controlador de red', shortName: 'Control', description: 'Aumenta 10 % almacenamiento y venta, hasta 50 %.', icon: '⌘', cost: 100_000_000, capacity: 0, controllerBonus: 0.1, tech: 'thorium' },
  core: { kind: 'core', name: 'Núcleo térmico', shortName: 'Núcleo', description: 'Produce 7.500 calor/s durante 200 segundos: 1,5 M de calor.', icon: '✦', cost: 1_000_000, capacity: 20_000, production: 7_500, fuelCycles: 200, refuelCost: 1_000_000, tech: 'thermal' },
  thorium: { kind: 'thorium', name: 'Reactor de torio', shortName: 'Torio', description: 'Produce 25 M calor/s durante 75 segundos: 1.875 M de calor.', icon: '◈', cost: 1_250_000_000, capacity: 150_000_000, production: 25_000_000, fuelCycles: 75, refuelCost: 1_250_000_000, tech: 'thorium' },
  fusion: { kind: 'fusion', name: 'Reactor de fusión', shortName: 'Fusión', description: 'Produce 12,5 G calor/s durante 34 segundos: 425 G de calor.', icon: '✺', cost: 280_000_000_000, capacity: 75_000_000_000, production: 12_500_000_000, fuelCycles: 34, refuelCost: 280_000_000_000, tech: 'fusion' },
  generator: { kind: 'generator', name: 'Turbina generadora', shortName: 'Turbina', description: 'Convierte hasta 1.875 calor/s sin resistencia terminal y almacena únicamente el excedente térmico.', icon: 'ϟ', cost: 30_000, capacity: 4_000, thermalResistance: 0, conversionRate: 1_875, tech: 'thermal' },
  generator2: { kind: 'generator2', name: 'Turbina generadora II', shortName: 'Turbina II', description: 'Conversor avanzado de Fusión: transforma 6,25 M calor/s sin modificar las turbinas existentes.', icon: 'ϟ', cost: 37_500_000, capacity: 12_500_000, thermalResistance: 0, conversionRate: 6_250_000, tech: 'fusion' },
  cooler: { kind: 'cooler', name: 'Torre de enfriamiento', shortName: 'Enfriador', description: 'Disipa hasta 50.000 calor/s adyacente.', icon: '❄', cost: 1_000_000, capacity: 0, coolingRate: 50_000, tech: 'thorium' },
  exchanger: { kind: 'exchanger', name: 'Intercambiador', shortName: 'Interc.', description: 'Nodo térmico de 2 M con resistencia 2,24; solo aumenta mediante sus propias mejoras.', icon: '⇄', cost: 50_000_000, capacity: 2_000_000, referenceTransferRate: 200_000, thermalResistance: resistanceFromCapacityAndFlow(2_000_000, 200_000), tech: 'thorium' },
  pipe: { kind: 'pipe', name: 'Tubería térmica', shortName: 'Tubería', description: 'Conductor de 300.000 de capacidad y resistencia térmica 1,23.', icon: '━', cost: 10_000_000, capacity: 300_000, referenceTransferRate: 50_000, thermalResistance: resistanceFromCapacityAndFlow(300_000, 50_000), tech: 'thorium' },
  pipe2: { kind: 'pipe2', name: 'Tubería térmica II', shortName: 'Tubería II', description: 'Red presurizada de Fusión: extrae calor desde las fuentes más calientes y lo bombea hacia turbinas con demanda.', icon: '═', cost: 2_240_000_000, capacity: 75_000_000_000, referenceTransferRate: 12_500_000_000, thermalResistance: 0, tech: 'fusion' },
  accumulator: { kind: 'accumulator', name: 'Acumulador térmico', shortName: 'Depósito', description: 'Almacena 10 M con resistencia térmica 24,75.', icon: '▣', cost: 250_000_000, capacity: 10_000_000, referenceTransferRate: 100_000, thermalResistance: resistanceFromCapacityAndFlow(10_000_000, 100_000), tech: 'thorium' },
}
export { COMPONENT_ORDER }
