import { beforeEach, describe, expect, it, vi } from 'vitest'
import { AUTO_REBUILD_COSTS, ECONOMY, LIFETIME_ORDER, TECHNOLOGIES, levelMultiplier } from './balance'
import { COMPONENTS } from './catalog'
import { buyDesertSector, claimContract, createInitialState, demolitionRefund, globalSalesCapacity, globalStorageCapacity, isComponentUnlocked, placeTile, refuelTile, repairTile, sectorEnergyStored, sellStoredEnergy, sellTile, simulateMany, simulateTick, switchSector } from './engine'
import { importGame, normalizeGameState, simulateOffline } from './persistence'
import { canUnlockAutoRebuild, canUnlockTech, fuelCapacity, nextUpgradeGainPercent, unlockAutoRebuild, unlockTech, upgradeBuildingTrack, upgradeBuildingType, upgradeCost } from './research'
import type { GameState } from './types'
import { buildIsland } from '../ui/island'

function rich() { return { ...createInitialState(), credits: 1_000_000 } }
function unlocked() { const state = rich(); return { ...state, unlockedTechs: { solar: true, thermal: true, logistics: true, automation: true, thorium: true, fusion: true, expansion: true } } }
function withStored(state: GameState, energyStored: number): GameState { return { ...state, sectorEconomies: { ...state.sectorEconomies, [state.activeSector]: { ...state.sectorEconomies[state.activeSector], energyStored } } } }

describe('economy v2', () => {
  it('starts with five credits and separate resource stores', () => { const state = createInitialState(); expect(state.credits).toBe(5); expect(sectorEnergyStored(state)).toBe(0); expect(state.researchPoints).toBe(0); expect(state.version).toBe(13) })
  it('uses an irregular 36-cell coast for new games', () => { const cells = buildIsland(10, 8, 'coast').tiles.filter((tile) => tile.gridIndex !== null); expect(cells).toHaveLength(36); const rowWidths = new Set(cells.map((tile) => tile.y).map((row) => cells.filter((tile) => tile.y === row).length)); expect(rowWidths.size).toBeGreaterThan(2) })
  it('keeps thermal pieces locked behind RP technology', () => { const state = rich(); expect(isComponentUnlocked(state, 'core')).toBe(false); expect(placeTile(state, 0, 'core')).toBe(state) })
  it('unlocks a technology only with RP and its prerequisite', () => { let state = { ...rich(), researchPoints: TECHNOLOGIES.solar.cost }; expect(canUnlockTech(state, 'solar')).toBe(true); state = unlockTech(state, 'solar'); expect(state.unlockedTechs.solar).toBe(true); expect(state.researchPoints).toBe(0); expect(isComponentUnlocked(state, 'solar')).toBe(true) })
  it('does not let money bypass research', () => { expect(canUnlockTech(rich(), 'solar')).toBe(false) })
  it('stores production but earns nothing without a sales office', () => { let state = placeTile(rich(), 0, 'wind'); state = { ...state, credits: 0 }; const result = simulateTick(state); expect(result.report.producedEnergy).toBeCloseTo(0.2); expect(result.report.soldEnergy).toBe(0); expect(sectorEnergyStored(result.state)).toBeCloseTo(0.2); expect(result.state.credits).toBe(0) })
  it('manual sale drains the entire local bank in one press', () => { let state = withStored({ ...createInitialState(), credits: 2 }, 7.5); state = sellStoredEnergy(state); expect(sectorEnergyStored(state)).toBe(0); expect(state.credits).toBe(9.5); expect(state.totalEnergySold).toBe(7.5) })
  it('wastes overflow without selling when storage is full and there is no office', () => { let state = unlocked(); for (let i = 0; i < 20; i++) state = placeTile(state, i, 'solar'); state = withStored({ ...state, credits: 0 }, 10); const result = simulateTick(state); expect(result.report.wastedEnergy).toBe(20); expect(result.report.soldEnergy).toBe(0); expect(sectorEnergyStored(result.state)).toBe(10) })
  it('uses batteries and offices as local capacities', () => { let state = unlocked(); state = placeTile(state, 0, 'battery'); state = placeTile(state, 1, 'sales'); expect(globalStorageCapacity(state)).toBe(110); expect(globalSalesCapacity(state)).toBe(4) })
  it('sales offices sell before remaining energy enters the local bank', () => { let state = unlocked(); state = placeTile(state, 0, 'sales'); state = withStored({ ...state, credits: 0 }, 7); const result = simulateTick(state); expect(result.report.soldEnergy).toBe(4); expect(sectorEnergyStored(result.state)).toBe(3); expect(result.state.credits).toBe(4) })
  it('does not cap same-tick sales at the storage capacity', () => { let state = unlocked(); for (let i = 0; i < 20; i++) state = placeTile(state, i, 'solar'); for (let i = 20; i < 25; i++) state = placeTile(state, i, 'sales'); state = { ...state, credits: 0 }; const result = simulateTick(state); expect(result.report.producedEnergy).toBe(20); expect(result.report.soldEnergy).toBe(20); expect(sectorEnergyStored(result.state)).toBe(0); expect(result.state.credits).toBe(20) })
  it('generates RP only from research facilities', () => { let state = rich(); state = placeTile(state, 0, 'wind'); expect(simulateTick(state).report.generatedResearch).toBe(0); state = placeTile(state, 1, 'research'); expect(simulateTick(state).report.generatedResearch).toBeCloseTo(0.05) })
  it('converts local reactor heat through four adjacent turbines', () => { let state = unlocked(); state = placeTile(state, 9, 'core'); for (const index of [1, 8, 10, 17]) state = placeTile(state, index, 'generator'); const result = simulateTick(state); expect(result.report.thermalEnergy).toBe(8); expect(result.state.tiles[9]?.heat).toBe(0) })
  it('damages rather than destroys an overheated reactor', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateMany(state, 7); expect(state.tiles[0]).toMatchObject({ kind: 'core', damaged: true, enabled: false }); expect(state.incidents).toBe(1) })
  it('repairs a damaged reactor for 35 percent', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateMany(state, 7); const before = state.credits; state = repairTile(state, 0); expect(state.tiles[0]).toMatchObject({ damaged: false, enabled: true, heat: 0 }); expect(before - state.credits).toBe(Math.ceil(COMPONENTS.core.cost * ECONOMY.repairRate)) })
  it('consumes exactly one second of autonomy per active tick', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateTick(state).state; expect(state.tiles[0]?.fuel).toBe(89) })
  it('wind and solar consume lifetime and stop after expiring', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 1 } : tile) }; state = simulateTick(state).state; expect(state.tiles[0]?.fuel).toBe(0); const stopped = simulateTick(state); expect(stopped.report.directEnergy).toBe(0) })
  it('stops an empty reactor without its auto rebuild research', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const result = simulateTick(state); expect(result.report.heatProduction).toBe(0); expect(result.state.tiles[0]?.fuel).toBe(0) })
  it('manually rebuilds only an expired producer for its full construction cost', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); expect(refuelTile(state, 0)).toBe(state); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const before = state.credits; state = refuelTile(state, 0); expect(state.tiles[0]?.fuel).toBe(90); expect(before - state.credits).toBe(COMPONENTS.core.cost) })
  it('rebuilds an expired tile from build mode only with the same component type', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const occupied = state; expect(placeTile(state, 0, 'solar')).toBe(occupied); const before = state.credits; state = placeTile(state, 0, 'wind'); expect(state.tiles[0]?.kind).toBe('wind'); expect(state.tiles[0]?.fuel).toBe(10); expect(before - state.credits).toBe(COMPONENTS.wind.cost) })
  it('refunds nothing for durable producers and 85 percent for other pieces', () => { for (const kind of LIFETIME_ORDER) expect(demolitionRefund(kind)).toBe(0); expect(demolitionRefund('battery')).toBe(85); let state = unlocked(); state = placeTile(state, 0, 'wind'); const afterBuild = state.credits; state = sellTile(state, 0); expect(state.credits).toBe(afterBuild); state = placeTile(state, 0, 'battery'); const beforeSale = state.credits; state = sellTile(state, 0); expect(state.credits - beforeSale).toBe(85) })
  it('unlocks auto rebuild separately per type, pays each rebuild, and renews its visual identity', () => { let state = { ...unlocked(), researchPoints: AUTO_REBUILD_COSTS.wind! }; expect(canUnlockAutoRebuild(state, 'wind')).toBe(true); state = unlockAutoRebuild(state, 'wind'); expect(state.autoRebuilds.wind).toBe(true); expect(state.autoRebuilds.solar).toBe(false); state = placeTile(state, 0, 'wind'); const expiredId = state.tiles[0]?.id; state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const before = state.credits; const result = simulateTick(state); expect(result.report.directEnergy).toBeCloseTo(0.2); expect(result.state.tiles[0]?.fuel).toBe(9); expect(result.state.tiles[0]?.id).not.toBe(expiredId); expect(before - result.state.credits).toBe(1) })
  it('keeps wind auto rebuild accessible and prices researched producers at three times their technology', () => { expect(AUTO_REBUILD_COSTS.wind).toBe(15); expect(AUTO_REBUILD_COSTS.solar).toBeGreaterThanOrEqual(TECHNOLOGIES.solar.cost * 3); expect(AUTO_REBUILD_COSTS.core).toBeGreaterThanOrEqual(TECHNOLOGIES.thermal.cost * 3); expect(AUTO_REBUILD_COSTS.thorium).toBeGreaterThanOrEqual(TECHNOLOGIES.thorium.cost * 3); expect(AUTO_REBUILD_COSTS.fusion).toBeGreaterThanOrEqual(TECHNOLOGIES.fusion.cost * 3) })
  it('gives base producers a decreasing 150 to 200 percent gross return', () => { const returns = LIFETIME_ORDER.map((kind) => { const def = COMPONENTS[kind]; return ((def.directEnergy ?? def.production ?? 0) * (def.fuelCycles ?? 0)) / def.cost }); expect(returns[0]).toBeCloseTo(2); expect(returns.at(-1)).toBeCloseTo(1.5); expect(returns.every((value) => value >= 1.5 && value <= 2)).toBe(true); expect(returns.every((value, index) => index === 0 || value <= returns[index - 1])).toBe(true) })
  it('upgrades every unit of a type on the active map while build cost stays fixed', () => { let state = rich(); const cost = upgradeCost(state, 'wind'); state = upgradeBuildingType(state, 'wind'); expect(state.sectorEconomies.coast.buildingLevels.wind).toBe(2); expect(state.sectorEconomies.desert.buildingLevels.wind).toBe(1); expect(rich().credits - state.credits).toBe(cost); expect(COMPONENTS.wind.cost).toBe(1) })
  it('charges the doubled upgrade price and reports the stronger next-level impact', () => { const state = createInitialState(); expect(upgradeCost(state, 'wind')).toBe(10); expect(nextUpgradeGainPercent(state, 'wind', 'output')).toBeCloseTo(35) })
  it('upgrades autonomy for current and future units on the active map', () => { let state = rich(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'wind'); const before = fuelCapacity(state, 'wind'); state = upgradeBuildingTrack(state, 'wind', 'autonomy'); const after = fuelCapacity(state, 'wind'); expect(after).toBeGreaterThan(before); expect(state.tiles[0]?.fuel).toBeCloseTo(after); expect(state.tiles[1]?.fuel).toBeCloseTo(after); state = placeTile(state, 2, 'wind'); expect(state.tiles[2]?.fuel).toBeCloseTo(after) })
  it('applies the stronger five and ten level milestones', () => { expect(levelMultiplier(5)).toBeCloseTo(Math.pow(1.35, 4) * 1.5); expect(levelMultiplier(10)).toBeCloseTo(Math.pow(1.35, 9) * 2.5) })
  it('requires both expansion research and money to buy the desert', () => { let state = rich(); expect(buyDesertSector(state)).toBe(state); state = { ...state, unlockedTechs: { ...state.unlockedTechs, expansion: true }, credits: ECONOMY.secondIslandCost }; state = buyDesertSector(state); expect(state.ownedSectors.desert).toBe(true) })
  it('simulates owned sectors in parallel but keeps their banks and offices separate', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'sales'); state = { ...state, ownedSectors: { coast: true, desert: true } }; state = switchSector(state, 'desert'); state = placeTile(state, 0, 'solar'); state = switchSector(state, 'coast'); const result = simulateTick(state); expect(result.report.producedEnergy).toBeCloseTo(1.45); expect(result.report.soldEnergy).toBeCloseTo(0.2); expect(result.state.sectorEconomies.coast.energyStored).toBe(0); expect(result.state.sectorEconomies.desert.energyStored).toBeCloseTo(1.25) })
  it('claims optional contracts without unlocking technology', () => { let state = createInitialState(); state = { ...state, activeContract: { ...state.activeContract, progress: state.activeContract.target } }; state = claimContract(state); expect(state.contractsCompleted).toBe(1); expect(state.unlockedTechs.solar).toBe(false) })
  it('caps contract RP below ten percent of the next technology', () => { let state = createInitialState(); state = { ...state, activeContract: { ...state.activeContract, progress: state.activeContract.target, rewardResearch: 999 } }; state = claimContract(state); expect(state.researchPoints).toBe(3) })
  it('simulates offline sales and research only when an office exists', () => { let state = rich(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'research'); state = placeTile(state, 2, 'sales'); const offline = simulateOffline(state, 10); expect(offline.summary.sold).toBeCloseTo(2); expect(offline.summary.research).toBeCloseTo(0.5) })
  it('migrates v12 saves into per-map economies and rejects malformed grids', () => { const old: any = { ...createInitialState(), version: 12, energyStored: 6, buildingLevels: emptyLevels(), capacityLevels: undefined, autonomyLevels: undefined, autoRebuilds: undefined }; delete old.sectorEconomies; delete old.sectorReports; const migrated = normalizeGameState(old); expect(migrated?.version).toBe(13); expect(migrated?.sectorEconomies.coast.energyStored).toBe(6); expect(migrated?.sectorEconomies.coast.capacityLevels.wind).toBe(1); expect(migrated?.autoRebuilds.wind).toBe(false); expect(normalizeGameState({ version: 9 })).toBeNull(); expect(normalizeGameState({ ...createInitialState(), tiles: [] })).toBeNull(); expect(importGame('bad')).toBeNull() })
})

describe('storage safety', () => {
  beforeEach(() => { vi.stubGlobal('localStorage', { getItem: vi.fn(() => null), setItem: vi.fn(), removeItem: vi.fn() }) })
  it('keeps the old save key untouched while evolving the v2 model', () => { expect(createInitialState().version).toBe(13) })
})

function emptyLevels() { return { wind: 1, solar: 1, battery: 1, controller: 1, sales: 1, research: 1, core: 1, thorium: 1, fusion: 1, exchanger: 1, pipe: 1, accumulator: 1, generator: 1, cooler: 1 } }
