import { beforeEach, describe, expect, it, vi } from 'vitest'
import { AUTO_REBUILD_COSTS, BOOST_TICKS_PER_SECOND, ECONOMY, GIFT_TICKS_PER_THERMAL_TECH, LIFETIME_ORDER, TECHNOLOGIES, levelMultiplier, offlineProductiveSeconds } from './balance'
import { COMPONENTS } from './catalog'
import { buyDesertSector, claimContract, createInitialState, demolitionRefund, globalSalesCapacity, globalStorageCapacity, isComponentUnlocked, placeTile, refuelTile, repairTile, sectorEnergyStored, sellStoredEnergy, sellTile, simulateMany, simulateSecond, simulateTick, switchSector, totalHeat } from './engine'
import { importGame, normalizeGameState, simulateOffline } from './persistence'
import { canUnlockAutoRebuild, canUnlockTech, componentCapacity, componentLevel, conversionRate, coolingRate, directEnergyRate, fuelCapacity, maxUpgradeLevel, nextUpgradeGainPercent, researchPerFacility, salesPerOffice, storagePerBattery, thermalResistance, thermalTransferRate, unlockAutoRebuild, unlockTech, upgradeBuildingTrack, upgradeBuildingType, upgradeCost } from './research'
import type { GameState } from './types'
import { buildIsland, environmentFor } from '../ui/island'
import { CYBERPUNK_ENVIRONMENT } from '../ui/pixel/cyberpunk'

function rich() { return { ...createInitialState(), credits: 1_000_000_000_000_000 } }
function unlocked(): GameState { const state = rich(); return { ...state, unlockedTechs: { solar: true, thermal: true, thorium: true, fusion: true, expansion: true } } }
function withStored(state: GameState, energyStored: number): GameState { return { ...state, sectorEconomies: { ...state.sectorEconomies, [state.activeSector]: { ...state.sectorEconomies[state.activeSector], energyStored } } } }

describe('economy v2', () => {
  it('starts with the promoted credits and separate resource stores', () => { const state = createInitialState(); expect(state.credits).toBe(ECONOMY.startingCredits); expect(state.credits).toBe(1); expect(sectorEnergyStored(state)).toBe(0); expect(state.researchPoints).toBe(0); expect(state.version).toBe(20) })
  it('uses an irregular 36-cell coast for new games', () => { const cells = buildIsland(10, 8, 'coast').tiles.filter((tile) => tile.gridIndex !== null); expect(cells).toHaveLength(36); const rowWidths = new Set(cells.map((tile) => tile.y).map((row) => cells.filter((tile) => tile.y === row).length)); expect(rowWidths.size).toBeGreaterThan(2) })
  it('renders the cyberpunk sector as two unequal, connected and non-rectangular buildable islands', () => { const state = { ...createInitialState(), activeSector: 'desert' as const }; const island = buildIsland(10, 8, 'desert'); const cells = island.tiles.filter((tile) => tile.gridIndex !== null); expect(cells).toHaveLength(72); expect(environmentFor(state)).toBe('futuristic'); expect(CYBERPUNK_ENVIRONMENT).toMatchObject({ decoration: 'pylon', terrain: { 3: '#c968b1', 4: '#080b22', 5: '#63a8b8', 7: '#73508c' } }); const positions = new Set(cells.map(({ x, y }) => `${x},${y}`)); const components: Array<Array<[number, number]>> = []; while (positions.size) { const pending = [positions.values().next().value as string]; positions.delete(pending[0]); const component: Array<[number, number]> = []; while (pending.length) { const current = pending.pop()!; const [x, y] = current.split(',').map(Number) as [number, number]; component.push([x, y]); for (const neighbor of [`${x - 1},${y}`, `${x + 1},${y}`, `${x},${y - 1}`, `${x},${y + 1}`]) if (positions.delete(neighbor)) pending.push(neighbor) } components.push(component) } components.sort((a, b) => b.length - a.length); expect(components.map((component) => component.length)).toEqual([48, 24]); for (const component of components) { const xs = component.map(([x]) => x); const ys = component.map(([, y]) => y); const boundingArea = (Math.max(...xs) - Math.min(...xs) + 1) * (Math.max(...ys) - Math.min(...ys) + 1); expect(boundingArea).toBeGreaterThan(component.length) } expect(cells.filter((tile) => tile.decor !== null).map((tile) => tile.gridIndex).sort((a, b) => a! - b!)).toEqual([10, 29, 43, 68]); expect(buildIsland(10, 8, 'desert', [48]).tiles.some((tile) => tile.gridIndex === 48)).toBe(true) })
  it('keeps thermal pieces locked behind RP technology', () => { const state = rich(); expect(isComponentUnlocked(state, 'core')).toBe(false); expect(placeTile(state, 0, 'core')).toBe(state) })
  it('unlocks a technology only with RP and its prerequisite', () => { let state = { ...rich(), researchPoints: TECHNOLOGIES.solar.cost }; expect(canUnlockTech(state, 'solar')).toBe(true); state = unlockTech(state, 'solar'); expect(state.unlockedTechs.solar).toBe(true); expect(state.researchPoints).toBe(0); expect(isComponentUnlocked(state, 'solar')).toBe(true) })
  it('unlocks territorial expansion with RP alone, independently from the technology chain', () => { let state = { ...createInitialState(), researchPoints: TECHNOLOGIES.expansion.cost }; expect(Object.values(state.unlockedTechs).every((unlocked) => !unlocked)).toBe(true); expect(canUnlockTech(state, 'expansion')).toBe(true); state = unlockTech(state, 'expansion'); expect(state.unlockedTechs.expansion).toBe(true); expect(state.unlockedTechs.fusion).toBe(false); expect(state.researchPoints).toBe(0) })
  it('does not let money bypass research', () => { expect(canUnlockTech(rich(), 'solar')).toBe(false) })
  it('stores production but earns nothing without a sales office', () => { let state = placeTile(rich(), 0, 'wind'); state = { ...state, credits: 0 }; const result = simulateTick(state); expect(result.report.producedEnergy).toBeCloseTo(0.2); expect(result.report.soldEnergy).toBe(0); expect(sectorEnergyStored(result.state)).toBeCloseTo(0.2); expect(result.state.credits).toBe(0) })
  it('manual sale drains the entire local bank in one press', () => { let state = withStored({ ...createInitialState(), credits: 2 }, 7.5); state = sellStoredEnergy(state); expect(sectorEnergyStored(state)).toBe(0); expect(state.credits).toBe(9.5); expect(state.totalEnergySold).toBe(7.5) })
  it('wastes overflow without selling when storage is full and there is no office', () => { let state = unlocked(); for (let i = 0; i < 20; i++) state = placeTile(state, i, 'solar'); state = withStored({ ...state, credits: 0 }, ECONOMY.baseStorage); const result = simulateTick(state); expect(result.report.wastedEnergy).toBe(2_000); expect(result.report.soldEnergy).toBe(0); expect(sectorEnergyStored(result.state)).toBe(ECONOMY.baseStorage) })
  it('uses batteries and offices as local capacities', () => { let state = rich(); state = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true } }; state = placeTile(state, 0, 'battery'); state = placeTile(state, 1, 'sales'); expect(globalStorageCapacity(state)).toBe(ECONOMY.baseStorage + COMPONENTS.battery.storageCapacity!); expect(globalSalesCapacity(state)).toBe(COMPONENTS.sales.salesRate) })
  it('sales offices sell before remaining energy enters the local bank', () => { let state = rich(); state = placeTile(state, 0, 'sales'); state = withStored({ ...state, credits: 0 }, 20_000); const result = simulateTick(state); expect(result.report.soldEnergy).toBe(50); expect(sectorEnergyStored(result.state)).toBe(20); expect(result.report.wastedEnergy).toBe(19_930); expect(result.state.credits).toBe(50) })
  it('does not cap same-tick sales at the storage capacity', () => { let state = unlocked(); for (let i = 0; i < 20; i++) state = placeTile(state, i, 'solar'); for (let i = 20; i < 25; i++) state = placeTile(state, i, 'sales'); state = { ...state, credits: 0 }; const result = simulateTick(state); expect(result.report.producedEnergy).toBe(2_000); expect(result.report.soldEnergy).toBe(250); expect(result.report.soldEnergy).toBeGreaterThan(ECONOMY.baseStorage); expect(sectorEnergyStored(result.state)).toBe(ECONOMY.baseStorage); expect(result.state.credits).toBe(250) })
  it('generates RP only from research facilities', () => { let state = rich(); state = placeTile(state, 0, 'wind'); expect(simulateTick(state).report.generatedResearch).toBe(0); state = placeTile(state, 1, 'research'); expect(simulateTick(state).report.generatedResearch).toBeCloseTo(1) })
  it('fully converts an exactly matched core through four fair terminal turbines', () => { let state = rich(); state = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true } }; state = placeTile(state, 9, 'core'); for (const index of [1, 8, 10, 17]) state = placeTile(state, index, 'generator'); const result = simulateTick(state); expect(result.report.thermalEnergy).toBeCloseTo(COMPONENTS.core.production!); expect(totalHeat(result.state)).toBeCloseTo(0); for (const index of [1, 8, 10, 17]) expect(result.state.tiles[index]?.flow).toBeCloseTo(COMPONENTS.generator.conversionRate!); const sustained = simulateMany(result.state, 20); expect(totalHeat(sustained)).toBeCloseTo(0); expect(sustained.incidents).toBe(0) })
  it('fully and fairly converts the promoted thorium output through tier-II turbines with spare capacity', () => { let state = rich(); state = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true, thorium: true, fusion: true } }; state = placeTile(state, 9, 'thorium'); for (const index of [1, 8, 10, 17]) state = placeTile(state, index, 'generator2'); const result = simulateTick(state); expect(result.report.thermalEnergy).toBeCloseTo(COMPONENTS.thorium.production!); expect(totalHeat(result.state)).toBeCloseTo(0); for (const index of [1, 8, 10, 17]) expect(result.state.tiles[index]?.flow).toBeCloseTo(COMPONENTS.thorium.production! / 4); const sustained = simulateMany(result.state, 20); expect(totalHeat(sustained)).toBeCloseTo(0); expect(sustained.incidents).toBe(0) })
  it('converts demand first and stores only a balanced thermal surplus', () => { let state = rich(); state = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true }, sectorEconomies: { ...state.sectorEconomies, coast: { ...state.sectorEconomies.coast, buildingLevels: { ...state.sectorEconomies.coast.buildingLevels, core: 2 } } } }; state = placeTile(state, 9, 'core'); for (const index of [1, 8, 10, 17]) state = placeTile(state, index, 'generator'); const result = simulateTick(state); const expectedConversion = COMPONENTS.generator.conversionRate! * 4; const expectedSurplus = COMPONENTS.core.production! * levelMultiplier(2) - expectedConversion; expect(result.report.thermalEnergy).toBeCloseTo(expectedConversion); expect(totalHeat(result.state)).toBeCloseTo(expectedSurplus, 6); const turbineHeat = [1, 8, 10, 17].map((index) => result.state.tiles[index]?.heat ?? 0); expect(Math.max(...turbineHeat) - Math.min(...turbineHeat)).toBeCloseTo(0, 8); expect(turbineHeat[0]).toBeGreaterThan(0) })
  it('keeps pipe resistance as a remote conversion bottleneck at the first thermal tier', () => { let state = unlocked(); state = placeTile(state, 9, 'core'); state = placeTile(state, 10, 'pipe'); state = placeTile(state, 11, 'generator2'); state = { ...state, unlockedTechs: { ...state.unlockedTechs, thorium: false, fusion: false } }; const result = simulateTick(state); expect(result.report.thermalEnergy).toBeGreaterThan(0); expect(result.report.thermalEnergy).toBeLessThan(Math.min(COMPONENTS.core.production!, conversionRate(state, 'generator2'))); expect(totalHeat(result.state) + result.report.thermalEnergy).toBeCloseTo(COMPONENTS.core.production!, 6) })
  it('actively pumps heat through a continuous Pipe II route toward converter demand', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = placeTile(state, 1, 'pipe2'); state = placeTile(state, 2, 'pipe2'); state = placeTile(state, 3, 'generator'); const result = simulateTick(state); expect(result.report.thermalEnergy).toBeCloseTo(conversionRate(state)); expect(result.state.tiles[1]?.flow).toBeGreaterThan(0); expect(result.state.tiles[2]?.flow).toBeGreaterThan(0); expect(totalHeat(result.state) + result.report.thermalEnergy).toBeCloseTo(COMPONENTS.core.production!, 6) })
  it('converts stored turbine heat, keeps excess, and can overload after conversion', () => { let state = unlocked(); state = placeTile(state, 0, 'generator'); const rate = conversionRate(state); state = { ...state, tiles: state.tiles.map((tile, index) => index === 0 && tile ? { ...tile, heat: rate + 500 } : tile) }; let result = simulateTick(state); expect(result.report.thermalEnergy).toBe(rate); expect(result.state.tiles[0]?.heat).toBeCloseTo(500); state = { ...result.state, tiles: result.state.tiles.map((tile, index) => index === 0 && tile ? { ...tile, heat: componentCapacity(result.state, 'generator') + rate + 1 } : tile) }; result = simulateTick(state); expect(result.state.tiles[0]).toMatchObject({ damaged: true, enabled: false }); expect(result.state.tiles[0]?.heat).toBeCloseTo(componentCapacity(result.state, 'generator') + 1) })
  it('conserves generated heat through diffusion, conversion and cooling', () => {
    let state = rich()
    state = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true, thorium: true } }
    state = placeTile(state, 9, 'core')
    state = placeTile(state, 10, 'pipe')
    state = placeTile(state, 11, 'generator')
    state = placeTile(state, 18, 'cooler')
    const before = totalHeat(state)
    const result = simulateTick(state)
    const accounted = totalHeat(result.state) + result.report.thermalEnergy + result.report.cooledHeat
    expect(accounted).toBeCloseTo(before + result.report.heatProduction, 6)
  })
  it('never rescales existing infrastructure when Thorium or Fusion unlocks', () => {
    let state = unlocked()
    state = placeTile(state, 0, 'pipe')
    state = placeTile(state, 1, 'exchanger')
    state = placeTile(state, 2, 'accumulator')
    state = placeTile(state, 3, 'cooler')
    state = placeTile(state, 4, 'battery')
    state = placeTile(state, 5, 'pipe2')
    const thermal = { ...state, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true, thorium: false, fusion: false } }
    const thorium = { ...thermal, unlockedTechs: { ...thermal.unlockedTechs, thorium: true } }
    const fusion = { ...thorium, unlockedTechs: { ...thorium.unlockedTechs, fusion: true } }
    for (const kind of ['pipe', 'pipe2', 'exchanger', 'accumulator', 'generator', 'generator2'] as const) {
      expect(componentCapacity(thorium, kind)).toBe(componentCapacity(thermal, kind))
      expect(componentCapacity(fusion, kind)).toBe(componentCapacity(thermal, kind))
    }
    expect(conversionRate(thorium)).toBe(conversionRate(thermal))
    expect(conversionRate(fusion, 'generator2')).toBe(conversionRate(thermal, 'generator2'))
    expect(coolingRate(thorium)).toBe(coolingRate(thermal))
    expect(coolingRate(fusion)).toBe(coolingRate(thermal))
    expect(storagePerBattery(thorium)).toBe(storagePerBattery(thermal))
    expect(storagePerBattery(fusion)).toBe(storagePerBattery(thermal))
    expect(thermal.tiles.slice(0, 6).map((tile) => tile?.kind)).toEqual(['pipe', 'exchanger', 'accumulator', 'cooler', 'battery', 'pipe2'])
  })
  it('unlocks the advanced Thorium network while keeping Turbine II locked', () => { const state = createInitialState(); const thermal = { ...state, credits: 1_000_000_000, unlockedTechs: { ...state.unlockedTechs, solar: true, thermal: true } }; for (const kind of ['thorium', 'generator2', 'cooler', 'pipe', 'exchanger', 'accumulator', 'controller', 'sales2', 'research2'] as const) expect(isComponentUnlocked(thermal, kind)).toBe(false); let thorium = { ...thermal, unlockedTechs: { ...thermal.unlockedTechs, thorium: true } }; for (const kind of ['thorium', 'cooler', 'pipe', 'exchanger', 'accumulator', 'controller', 'sales2', 'research2'] as const) expect(isComponentUnlocked(thorium, kind)).toBe(true); expect(isComponentUnlocked(thorium, 'generator2')).toBe(false); thorium = upgradeBuildingTrack(thorium, 'sales2', 'output'); expect(thorium.sectorEconomies.coast.buildingLevels.sales2).toBe(2); expect(thorium.sectorEconomies.coast.buildingLevels.sales).toBe(1) })
  it('unlocks Turbine II and Pipe II only with Fusion and keeps their levels independent from tier I', () => { let state = unlocked(); state = { ...state, unlockedTechs: { ...state.unlockedTechs, fusion: false } }; expect(isComponentUnlocked(state, 'generator')).toBe(true); expect(isComponentUnlocked(state, 'generator2')).toBe(false); expect(isComponentUnlocked(state, 'pipe')).toBe(true); expect(isComponentUnlocked(state, 'pipe2')).toBe(false); state = { ...state, unlockedTechs: { ...state.unlockedTechs, fusion: true } }; expect(isComponentUnlocked(state, 'generator2')).toBe(true); expect(isComponentUnlocked(state, 'pipe2')).toBe(true); state = upgradeBuildingTrack(state, 'generator2', 'output'); state = upgradeBuildingTrack(state, 'pipe2', 'output'); expect(state.sectorEconomies.coast.buildingLevels.generator2).toBe(2); expect(state.sectorEconomies.coast.buildingLevels.generator).toBe(1); expect(state.sectorEconomies.coast.buildingLevels.pipe2).toBe(2); expect(state.sectorEconomies.coast.buildingLevels.pipe).toBe(1) })
  it('adds tier-I and tier-II sales and research without scaling tier I', () => { let state = unlocked(); state = placeTile(state, 0, 'sales'); state = placeTile(state, 1, 'sales2'); state = placeTile(state, 2, 'research'); state = placeTile(state, 3, 'research2'); expect(globalSalesCapacity(state)).toBe(salesPerOffice(state, 'sales') + salesPerOffice(state, 'sales2')); const result = simulateTick(state); expect(result.report.generatedResearch).toBe(researchPerFacility(state, 'research') + researchPerFacility(state, 'research2')) })
  it('damages rather than destroys an overheated reactor', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateMany(state, 7); expect(state.tiles[0]).toMatchObject({ kind: 'core', damaged: true, enabled: false }); expect(state.incidents).toBe(1) })
  it('damages an overloaded pipe without silently deleting its heat', () => {
    let state = unlocked()
    state = placeTile(state, 9, 'pipe')
    const capacity = componentCapacity(state, 'pipe')
    state = { ...state, tiles: state.tiles.map((tile, index) => index === 9 && tile ? { ...tile, heat: capacity + 1 } : tile) }
    const before = totalHeat(state)
    const result = simulateTick(state)
    expect(result.state.tiles[9]).toMatchObject({ kind: 'pipe', damaged: true, enabled: false })
    expect(totalHeat(result.state)).toBeCloseTo(before, 6)
  })
  it('repairs a damaged reactor for 35 percent', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateMany(state, 7); const before = state.credits; state = repairTile(state, 0); expect(state.tiles[0]).toMatchObject({ damaged: false, enabled: true, heat: 0 }); expect(before - state.credits).toBe(Math.ceil(COMPONENTS.core.cost * ECONOMY.repairRate)) })
  it('consumes exactly one second of autonomy per active tick', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = simulateTick(state).state; expect(state.tiles[0]?.fuel).toBe(COMPONENTS.core.fuelCycles! - 1) })
  it('wind and solar consume lifetime and stop after expiring', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 1 } : tile) }; state = simulateTick(state).state; expect(state.tiles[0]?.fuel).toBe(0); const stopped = simulateTick(state); expect(stopped.report.directEnergy).toBe(0) })
  it('stops an empty reactor without its auto rebuild research', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const result = simulateTick(state); expect(result.report.heatProduction).toBe(0); expect(result.state.tiles[0]?.fuel).toBe(0) })
  it('manually rebuilds only an expired producer for its full construction cost', () => { let state = unlocked(); state = placeTile(state, 0, 'core'); expect(refuelTile(state, 0)).toBe(state); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const before = state.credits; state = refuelTile(state, 0); expect(state.tiles[0]?.fuel).toBe(COMPONENTS.core.fuelCycles); expect(before - state.credits).toBe(COMPONENTS.core.cost) })
  it('rebuilds an expired tile from build mode only with the same component type', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const occupied = state; expect(placeTile(state, 0, 'solar')).toBe(occupied); const before = state.credits; state = placeTile(state, 0, 'wind'); expect(state.tiles[0]?.kind).toBe('wind'); expect(state.tiles[0]?.fuel).toBe(10); expect(before - state.credits).toBe(COMPONENTS.wind.cost) })
  it('refunds nothing for durable producers and 85 percent for other pieces', () => { for (const kind of LIFETIME_ORDER) expect(demolitionRefund(kind)).toBe(0); expect(demolitionRefund('battery')).toBe(42_500); let state = unlocked(); state = placeTile(state, 0, 'wind'); const afterBuild = state.credits; state = sellTile(state, 0); expect(state.credits).toBe(afterBuild); state = placeTile(state, 0, 'battery'); const beforeSale = state.credits; state = sellTile(state, 0); expect(state.credits - beforeSale).toBe(42_500) })
  it('unlocks auto rebuild separately per type, pays each rebuild, and renews its visual identity', () => { let state = { ...unlocked(), researchPoints: AUTO_REBUILD_COSTS.wind! }; expect(canUnlockAutoRebuild(state, 'wind')).toBe(true); state = unlockAutoRebuild(state, 'wind'); expect(state.autoRebuilds.wind).toBe(true); expect(state.autoRebuilds.solar).toBe(false); state = placeTile(state, 0, 'wind'); const expiredId = state.tiles[0]?.id; state = { ...state, tiles: state.tiles.map((tile, i) => i === 0 && tile ? { ...tile, fuel: 0 } : tile) }; const before = state.credits; const result = simulateTick(state); expect(result.report.directEnergy).toBeCloseTo(0.2); expect(result.state.tiles[0]?.fuel).toBe(9); expect(result.state.tiles[0]?.id).not.toBe(expiredId); expect(before - result.state.credits).toBe(1) })
  it('uses the promoted auto rebuild research prices', () => { expect(AUTO_REBUILD_COSTS).toEqual({ wind: 15, solar: 3_000, core: 150_000, thorium: 9_000_000, fusion: 60_000_000 }) })
  it('gives base producers a decreasing 150 to 200 percent gross return', () => { const returns = LIFETIME_ORDER.map((kind) => { const def = COMPONENTS[kind]; return ((def.directEnergy ?? def.production ?? 0) * (def.fuelCycles ?? 0)) / def.cost }); expect(returns[0]).toBeCloseTo(2); expect(returns.at(-1)).toBeGreaterThanOrEqual(1.5); expect(returns.every((value) => value >= 1.5 && value <= 2)).toBe(true); expect(returns.every((value, index) => index === 0 || value <= returns[index - 1] + 0.02)).toBe(true) })
  it('upgrades every unit of a type on the active map while build cost stays fixed', () => { let state = rich(); const cost = upgradeCost(state, 'wind'); state = upgradeBuildingType(state, 'wind'); expect(state.sectorEconomies.coast.buildingLevels.wind).toBe(2); expect(state.sectorEconomies.desert.buildingLevels.wind).toBe(0); expect(rich().credits - state.credits).toBe(cost); expect(COMPONENTS.wind.cost).toBe(1) })
  it('starts Distrito Neón at level zero, keeps Costa upgrades, and reaches level fifteen', () => {
    let state = rich()
    state = upgradeBuildingTrack(state, 'wind', 'output')
    state = upgradeBuildingTrack(state, 'wind', 'output')
    expect(componentLevel(state, 'wind')).toBe(3)
    state = switchSector({ ...state, ownedSectors: { coast: true, desert: true } }, 'desert')
    expect(componentLevel(state, 'wind')).toBe(0)
    expect(directEnergyRate(state, 'wind')).toBeCloseTo(COMPONENTS.wind.directEnergy!)
    expect(maxUpgradeLevel(state)).toBe(15)
    for (let level = 0; level < 15; level += 1) state = upgradeBuildingTrack(state, 'wind', 'output')
    expect(componentLevel(state, 'wind')).toBe(15)
    expect(directEnergyRate(state, 'wind')).toBeCloseTo(COMPONENTS.wind.directEnergy! * levelMultiplier(16))
    expect(upgradeBuildingTrack(state, 'wind', 'output')).toBe(state)
    state = switchSector(state, 'coast')
    expect(componentLevel(state, 'wind')).toBe(3)
    expect(maxUpgradeLevel(state)).toBe(10)
  })
  it('uses the promoted first wind upgrade without raising its impact', () => { const state = createInitialState(); expect(upgradeCost(state, 'wind')).toBe(30); expect(nextUpgradeGainPercent(state, 'wind', 'output')).toBeCloseTo(35) })
  it('turns a conductor output upgrade into lower thermal resistance', () => { const state = rich(); const before = thermalResistance(state, 'pipe'); const upgraded = upgradeBuildingTrack(state, 'pipe', 'output'); expect(before / thermalResistance(upgraded, 'pipe')).toBeCloseTo(1.35) })
  it('turns a Pipe II output upgrade into more active throughput and lower positive resistance', () => { const state = rich(); const beforeTransfer = thermalTransferRate(state, 'pipe2'); const beforeResistance = thermalResistance(state, 'pipe2'); const upgraded = upgradeBuildingTrack(state, 'pipe2', 'output'); expect(thermalTransferRate(upgraded, 'pipe2') / beforeTransfer).toBeCloseTo(1.35); expect(beforeResistance / thermalResistance(upgraded, 'pipe2')).toBeCloseTo(1.35); expect(thermalResistance(upgraded, 'pipe2')).toBeGreaterThan(0) })
  it('upgrades autonomy for current and future units on the active map', () => { let state = rich(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'wind'); const before = fuelCapacity(state, 'wind'); state = upgradeBuildingTrack(state, 'wind', 'autonomy'); const after = fuelCapacity(state, 'wind'); expect(after).toBeGreaterThan(before); expect(state.tiles[0]?.fuel).toBeCloseTo(after); expect(state.tiles[1]?.fuel).toBeCloseTo(after); state = placeTile(state, 2, 'wind'); expect(state.tiles[2]?.fuel).toBeCloseTo(after) })
  it('applies the stronger five and ten level milestones', () => { expect(levelMultiplier(5)).toBeCloseTo(Math.pow(1.35, 4) * 1.5); expect(levelMultiplier(10)).toBeCloseTo(Math.pow(1.35, 9) * 2.5) })
  it('requires expansion research and money—but no other technology—to buy the desert', () => { let state = rich(); expect(buyDesertSector(state)).toBe(state); state = { ...createInitialState(), unlockedTechs: { ...createInitialState().unlockedTechs, expansion: true }, credits: ECONOMY.secondIslandCost }; state = buyDesertSector(state); expect(state.ownedSectors.desert).toBe(true); expect(state.unlockedTechs.fusion).toBe(false) })
  it('simulates owned sectors in parallel but keeps their banks and offices separate', () => { let state = unlocked(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'sales'); state = { ...state, ownedSectors: { coast: true, desert: true } }; state = switchSector(state, 'desert'); state = placeTile(state, 0, 'solar'); state = switchSector(state, 'coast'); const result = simulateTick(state); expect(result.report.producedEnergy).toBeCloseTo(125.2); expect(result.report.soldEnergy).toBeCloseTo(0.2); expect(result.state.sectorEconomies.coast.energyStored).toBe(0); expect(result.state.sectorEconomies.desert.energyStored).toBeCloseTo(ECONOMY.baseStorage) })
  it('claims optional contracts without unlocking technology', () => { let state = createInitialState(); state = { ...state, activeContract: { ...state.activeContract, progress: state.activeContract.target } }; state = claimContract(state); expect(state.contractsCompleted).toBe(1); expect(state.unlockedTechs.solar).toBe(false) })
  it('caps contract RP below ten percent of the next technology', () => { let state = createInitialState(); state = { ...state, activeContract: { ...state.activeContract, progress: state.activeContract.target, rewardResearch: 999 } }; state = claimContract(state); expect(state.researchPoints).toBe(TECHNOLOGIES.solar.cost * 0.1) })
  it('simulates offline sales and research only when an office exists', () => { let state = rich(); state = placeTile(state, 0, 'wind'); state = placeTile(state, 1, 'research'); state = placeTile(state, 2, 'sales'); const offline = simulateOffline(state, 20); expect(offline.summary.simulatedSeconds).toBe(10); expect(offline.summary.sold).toBeCloseTo(2); expect(offline.summary.research).toBeCloseTo(10) })
  it('pays a decreasing share of each hour spent away and nothing past the fourth', () => { expect(offlineProductiveSeconds(1_800)).toBe(900); expect(offlineProductiveSeconds(3_600)).toBe(1_800); expect(offlineProductiveSeconds(7_200)).toBe(2_700); expect(offlineProductiveSeconds(10_800)).toBe(3_060); expect(offlineProductiveSeconds(14_400)).toBe(3_420); expect(offlineProductiveSeconds(100_000)).toBe(3_420); expect(ECONOMY.maxOfflineSeconds).toBe(14_400) })
  it('grants exactly those productive seconds to the plant', () => { let state = rich(); state = placeTile(state, 1, 'research'); const online = simulateMany(state, 900); const offline = simulateOffline(state, 1_800).state; expect(offline.researchPoints).toBeCloseTo(online.researchPoints) })
  it('gifts boost ticks on every thermal technology and none on the others', () => {
    let state: GameState = { ...rich(), researchPoints: 1_000_000_000 }
    state = unlockTech(state, 'solar'); expect(state.giftTicks).toBe(0)
    state = unlockTech(state, 'expansion'); expect(state.giftTicks).toBe(0)
    state = unlockTech(state, 'thermal'); expect(state.giftTicks).toBe(GIFT_TICKS_PER_THERMAL_TECH)
    state = unlockTech(state, 'thorium'); state = unlockTech(state, 'fusion')
    expect(state.giftTicks).toBe(GIFT_TICKS_PER_THERMAL_TECH * 3)
  })

  it('spends gift ticks only while the boost runs and stops itself when they end', () => {
    const base: GameState = { ...rich(), giftTicks: 25, boostActive: false }
    // Apagado no gasta nada y avanza solo a la velocidad elegida.
    expect(simulateSecond(base).giftTicks).toBe(25)
    expect(simulateSecond(base).tick).toBe(base.tick + base.speed)
    // Encendido suma los ticks extra y descuenta los mismos del regalo.
    const first = simulateSecond({ ...base, boostActive: true })
    expect(first.tick).toBe(base.tick + base.speed + BOOST_TICKS_PER_SECOND)
    expect(first.giftTicks).toBe(15)
    const second = simulateSecond(first)
    const third = simulateSecond(second)
    expect(third.giftTicks).toBe(0)
    expect(third.boostActive).toBe(false)
    // En pausa el bonus no consume nada.
    expect(simulateSecond({ ...base, boostActive: true, paused: true }).giftTicks).toBe(25)
  })

  it('migrates legacy saves, grants merged Thorium to prior Automation owners, and rejects malformed grids', () => { const old: any = { ...createInitialState(), version: 12, energyStored: 6, buildingLevels: emptyLevels(), capacityLevels: undefined, autonomyLevels: undefined, autoRebuilds: undefined, unlockedTechs: { ...createInitialState().unlockedTechs, automation: true, thorium: false } }; delete old.sectorEconomies; delete old.sectorReports; delete old.debug; const migrated = normalizeGameState(old); expect(migrated?.version).toBe(20); expect(migrated?.unlockedTechs.thorium).toBe(true); expect(migrated?.sectorEconomies.coast.energyStored).toBe(6); expect(migrated?.sectorEconomies.coast.capacityLevels.wind).toBe(1); expect(migrated?.sectorEconomies.coast.buildingLevels.sales2).toBe(1); expect(migrated?.sectorEconomies.coast.buildingLevels.generator2).toBe(1); expect(migrated?.sectorEconomies.coast.buildingLevels.pipe2).toBe(1); expect(migrated?.sectorEconomies.desert.buildingLevels.wind).toBe(0); expect(migrated?.autoRebuilds.wind).toBe(false); expect(migrated?.debug.enabled).toBe(false); expect(normalizeGameState({ version: 9 })).toBeNull(); expect(normalizeGameState({ ...createInitialState(), tiles: [] })).toBeNull(); expect(importGame('bad')).toBeNull() })
  it('resets only Distrito Neón upgrades when migrating the previous save model', () => { const old: any = createInitialState(); old.version = 17; old.sectorEconomies.coast.buildingLevels.wind = 7; old.sectorEconomies.desert.buildingLevels.wind = 6; old.sectorEconomies.desert.capacityLevels.wind = 5; old.sectorEconomies.desert.autonomyLevels.wind = 4; const migrated = normalizeGameState(old); expect(migrated?.sectorEconomies.coast.buildingLevels.wind).toBe(7); expect(migrated?.sectorEconomies.desert.buildingLevels.wind).toBe(0); expect(migrated?.sectorEconomies.desert.capacityLevels.wind).toBe(0); expect(migrated?.sectorEconomies.desert.autonomyLevels.wind).toBe(0) })
  it('relocates buildings from the old cyberpunk shoreline without losing them', () => { const old: any = createInitialState(); old.version = 18; old.sectorLayouts.desert[48] = { id: 'legacy-wind', kind: 'wind', heat: 0, enabled: true, damaged: false, flow: 0, fuel: 5, autoRefuel: false }; const migrated = normalizeGameState(old); expect(migrated?.sectorLayouts.desert[40]).toMatchObject({ id: 'legacy-wind', kind: 'wind' }); expect(migrated?.sectorLayouts.desert[48]).toBeNull() })
})

describe('storage safety', () => {
  beforeEach(() => { vi.stubGlobal('localStorage', { getItem: vi.fn(() => null), setItem: vi.fn(), removeItem: vi.fn() }) })
  it('keeps the old save key untouched while evolving the v2 model', () => { expect(createInitialState().version).toBe(20) })
})

function emptyLevels() { return { wind: 1, solar: 1, battery: 1, controller: 1, sales: 1, sales2: 1, research: 1, research2: 1, core: 1, thorium: 1, fusion: 1, exchanger: 1, pipe: 1, pipe2: 1, accumulator: 1, generator: 1, generator2: 1, cooler: 1 } }
