import type { RefObject } from 'react'
import { ECONOMY } from '../../game/balance'
import { canAfford } from '../../game/debug'
import { isSectorUnlocked } from '../../game/engine'
import type { GameState, SectorKey } from '../../game/types'
import { formatDecimal, formatNumber } from '../format'
import { Sprite } from '../pixel/Sprite'
import { Sheet } from '../Sheet'
interface Props { game: GameState; importRef: RefObject<HTMLTextAreaElement | null>; onClose: () => void; onSector: (sector: SectorKey) => void; onBuySector: () => void; onTogglePause: () => void; onSpeed: (speed: 1 | 2 | 4) => void; onInstall: () => void; onCopySave: () => void; onImport: () => void; onReset: () => void; onToggleDebug: () => void; onOpenDebug: () => void }
export function MenuSheet({ game, importRef, onClose, onSector, onBuySector, onTogglePause, onSpeed, onInstall, onCopySave, onImport, onReset, onToggleDebug, onOpenDebug }: Props) {
  const desert = isSectorUnlocked(game, 'desert'); const canBuy = game.unlockedTechs.expansion && canAfford(game, ECONOMY.secondIslandCost)
  return <Sheet title="Menú" eyebrow="SISTEMA" onClose={onClose} className="menu">
    <section className="menu-block"><h3>Operación · {game.activeSector === 'coast' ? 'A-01 Costa' : 'B-02 Desierto'}</h3><div className="menu-speed" role="group" aria-label="Velocidad de simulación"><button className={`btn frame ${game.paused ? 'on' : ''}`} onClick={onTogglePause}>{game.paused ? 'Reanudar' : 'Pausa'}</button>{([1, 2, 4] as const).map((speed) => <button key={speed} className={`btn frame ${!game.paused && game.speed === speed ? 'on' : ''}`} onClick={() => onSpeed(speed)}>{speed}×</button>)}</div></section>
    <section className="menu-block"><h3>Sectores</h3><div className="sector-tabs"><button className={`btn frame ${game.activeSector === 'coast' ? 'on' : ''}`} onClick={() => onSector('coast')}><strong>A-01</strong>Costa</button><button className={`btn frame ${game.activeSector === 'desert' ? 'on' : ''}`} disabled={!desert} onClick={() => onSector('desert')}><strong>B-02</strong>{desert ? 'Desierto · solar +25 %' : 'Bloqueado'}</button></div>{!desert && <button className="btn frame gold wide" disabled={!canBuy} onClick={onBuySector}>{!game.unlockedTechs.expansion ? 'Requiere Expansión territorial' : `Comprar isla · ₡ ${formatNumber(ECONOMY.secondIslandCost)}`}</button>}<p className="hint">Los sectores comprados producen en paralelo.</p></section>
    <section className="menu-block telemetry"><h3>Telemetría</h3><div><span>Ciclos</span><strong>{formatNumber(game.tick)}</strong></div><div><span>Energía producida</span><strong>{formatDecimal(game.totalEnergy)}</strong></div><div><span>Energía vendida</span><strong>{formatDecimal(game.totalEnergySold)}</strong></div><div><span>Averías</span><strong className={game.incidents ? 'danger-text' : ''}>{game.incidents}</strong></div><div><span>Combustible</span><strong>₡ {formatNumber(game.totalFuelSpent)}</strong></div><div><span>Reparaciones</span><strong>₡ {formatNumber(game.totalRepairSpent)}</strong></div></section>
    <section className="menu-block"><h3>Debug</h3><p className="hint">Sandbox local para probar economía, edificios e investigaciones.</p><div className="menu-actions"><button className={`btn frame ${game.debug.enabled ? 'on gold' : ''}`} onClick={onToggleDebug}>{game.debug.enabled ? 'Desactivar Debug' : 'Activar Debug'}</button><button className="btn frame" disabled={!game.debug.enabled} onClick={onOpenDebug}>Editar balance</button></div></section>
    <section className="menu-block"><h3>Guardado v2</h3><p className="hint">La partida se guarda automáticamente. Los códigos de la economía anterior no son compatibles.</p><div className="menu-actions"><button className="btn frame gold" onClick={onCopySave}>Copiar código</button><button className="btn frame" onClick={onInstall}>Instalar app</button></div><label className="import-field"><span>Importar código v2</span><textarea ref={importRef} placeholder="Pega aquí tu código…" rows={3} /></label><button className="btn frame wide" onClick={onImport}>Importar partida</button></section>
    <button className="text-btn danger-text" onClick={onReset}>Reiniciar progreso</button>
  </Sheet>
}
